application: wiki-zhongjun-tk
version: 1
runtime: python27
threadsafe: yes
api_version: 1

default_expiration: "7d"

handlers:
- url: /gae-wiki-static/
  static_dir: gaewiki/static
  secure: always
- url: /favicon.ico
  static_files: gaewiki/static/favicon.ico
  upload: gaewiki/static/favicon.ico
  secure: always
- url: .*
  script: gaewiki.application
  secure: always

libraries:
- name: django
  version: "1.2"
